"""Generate a synthetic demo dataset for dinov2_retrieval.

Writes, inside DATA_DIR (default ./data):

    reference/manifest.csv, reference/wine-NNN/photo-N.jpg   25 wines, 50 photos
    evaluation/queries.csv, evaluation/images/query-NNN.jpg  25 labelled queries
    requests/search-request.json                             example search request

wine-001 is derived from queries/test.jpeg (must exist); the other wines are
drawn "labels" made of random shapes. Queries are harder variants of the
reference photos: smaller, rotated, blurred, re-lit and placed on a background.

The images are synthetic: they check that indexing, search and evaluation work
end to end, and say nothing about DINOv2 quality on real bottle photos.

Existing reference/manifest.csv or evaluation/queries.csv are never
overwritten without --force, so a real dataset is not replaced by accident.

    python examples/generate_demo_data.py [DATA_DIR] [--force]
"""

from __future__ import annotations

import argparse
import csv
import json
import random
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageEnhance, ImageFilter, ImageOps

GRAPES = ["cabernet", "merlot", "syrah", "pinot-noir", "riesling", "chardonnay"]
CONTAINER_DATA_ROOT = "/data"
WINE_COUNT = 25
DEMO_NOTICE = """Synthetic demo data generated by examples/generate_demo_data.py.
It checks that the pipeline works; it says nothing about DINOv2 quality.
Replace it with real photos as described in README.md ("Реальный датасет").
"""


def label(seed: int) -> Image.Image:
    rng = random.Random(seed)
    background = tuple(rng.randint(150, 250) for _ in range(3))
    accent = tuple(rng.randint(10, 140) for _ in range(3))
    image = Image.new("RGB", (320, 420), background)
    draw = ImageDraw.Draw(image)
    margin = rng.randint(12, 30)
    draw.rectangle(
        (margin, margin, 320 - margin, 420 - margin),
        outline=accent,
        width=rng.randint(3, 9),
    )
    for _ in range(rng.randint(2, 5)):
        x0, y0 = rng.randint(40, 200), rng.randint(40, 300)
        shape = (x0, y0, x0 + rng.randint(40, 110), y0 + rng.randint(30, 100))
        color = tuple(rng.randint(0, 255) for _ in range(3))
        if rng.random() < 0.5:
            draw.ellipse(shape, fill=color)
        else:
            draw.rectangle(shape, fill=color)
    for row in range(rng.randint(3, 6)):
        y = 300 + row * 16
        draw.line((60, y, 60 + rng.randint(80, 200), y), fill=accent, width=6)
    return image


def variant(image: Image.Image, seed: int) -> Image.Image:
    """Another reference photo of the same bottle: crop, rotation, lighting."""

    rng = random.Random(seed)
    width, height = image.size
    dx, dy = int(width * 0.06), int(height * 0.06)
    cropped = image.crop(
        (
            rng.randint(0, dx),
            rng.randint(0, dy),
            width - rng.randint(0, dx),
            height - rng.randint(0, dy),
        )
    )
    rotated = cropped.rotate(rng.uniform(-6, 6), expand=False, fillcolor=(90, 90, 90))
    return ImageEnhance.Brightness(rotated).enhance(rng.uniform(0.8, 1.15))


def user_photo(image: Image.Image, seed: int) -> Image.Image:
    """A "user photo": the label smaller, tilted, blurred and on a background."""

    rng = random.Random(seed)
    canvas_color = tuple(rng.randint(20, 90) for _ in range(3))
    canvas = Image.new("RGB", (400, 520), canvas_color)
    scale = rng.uniform(0.65, 0.9)
    label_image = image.resize(
        (int(image.width * scale), int(image.height * scale)), Image.Resampling.BICUBIC
    )
    label_image = label_image.rotate(
        rng.uniform(-12, 12), expand=True, fillcolor=canvas_color
    )
    x = rng.randint(0, max(0, canvas.width - label_image.width))
    y = rng.randint(0, max(0, canvas.height - label_image.height))
    canvas.paste(label_image, (x, y))
    canvas = ImageEnhance.Brightness(canvas).enhance(rng.uniform(0.7, 1.2))
    canvas = ImageEnhance.Contrast(canvas).enhance(rng.uniform(0.75, 1.15))
    return canvas.filter(ImageFilter.GaussianBlur(rng.uniform(0.5, 1.8)))


def build_wines(data_dir: Path) -> list[tuple[str, str, Image.Image, list[Image.Image]]]:
    query = ImageOps.exif_transpose(Image.open(data_dir / "queries" / "test.jpeg"))
    query = query.convert("RGB")
    wines = [("wine-001", "cabernet-2020", query, [query.copy(), variant(query, 1)])]
    for index in range(2, WINE_COUNT + 1):
        base = label(index)
        photos = [base] + [
            variant(base, index * 10 + extra) for extra in range(index % 3)
        ]
        slug = f"{GRAPES[index % len(GRAPES)]}-{2000 + index}"
        wines.append((f"wine-{index:03d}", slug, base, photos))
    return wines


def write_reference(data_dir: Path, wines) -> str:
    reference = data_dir / "reference"
    rows = []
    for wine_id, slug, _, photos in wines:
        folder = reference / wine_id
        folder.mkdir(parents=True, exist_ok=True)
        for number, photo in enumerate(photos, start=1):
            path = folder / f"photo-{number}.jpg"
            photo.save(path, quality=92)
            rows.append((wine_id, slug, f"{CONTAINER_DATA_ROOT}/reference/{wine_id}/{path.name}"))
    write_csv(reference / "manifest.csv", ["wine_id", "slug", "image_uri"], rows)
    (reference / "DEMO.txt").write_text(DEMO_NOTICE, encoding="utf-8")
    return f"reference: {len(wines)} wines, {len(rows)} photos"


def write_evaluation(data_dir: Path, wines) -> str:
    evaluation = data_dir / "evaluation"
    images = evaluation / "images"
    images.mkdir(parents=True, exist_ok=True)
    rows = []
    for number, (wine_id, _, base, _) in enumerate(wines, start=1):
        path = images / f"query-{number:03d}.jpg"
        user_photo(base, 1000 + number).save(path, quality=75)
        rows.append((f"{CONTAINER_DATA_ROOT}/evaluation/images/{path.name}", wine_id))
    write_csv(evaluation / "queries.csv", ["query_image_uri", "wine_id"], rows)
    (evaluation / "DEMO.txt").write_text(DEMO_NOTICE, encoding="utf-8")
    return f"evaluation: {len(rows)} queries"


def write_request(data_dir: Path) -> str:
    requests = data_dir / "requests"
    requests.mkdir(exist_ok=True)
    request = {
        "request_id": "request-001",
        "image_uri": f"{CONTAINER_DATA_ROOT}/queries/test.jpeg",
        "top_k": 20,
    }
    (requests / "search-request.json").write_text(
        json.dumps(request, indent=2) + "\n", encoding="utf-8"
    )
    return "requests: search-request.json"


def write_csv(path: Path, header: list[str], rows) -> None:
    with path.open("w", newline="", encoding="utf-8") as csv_file:
        writer = csv.writer(csv_file)
        writer.writerow(header)
        writer.writerows(rows)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("data_dir", nargs="?", default="data", type=Path)
    parser.add_argument(
        "--force", action="store_true", help="overwrite existing manifest/queries"
    )
    args = parser.parse_args(argv)

    data_dir: Path = args.data_dir
    if not (data_dir / "queries" / "test.jpeg").is_file():
        print(f"{data_dir}/queries/test.jpeg is required", file=sys.stderr)
        return 1

    wines = build_wines(data_dir)
    parts = [
        (data_dir / "reference" / "manifest.csv", write_reference),
        (data_dir / "evaluation" / "queries.csv", write_evaluation),
        (data_dir / "requests" / "search-request.json", lambda d, _: write_request(d)),
    ]
    for marker, write in parts:
        if marker.exists() and not args.force:
            print(f"skipped: {marker} exists (use --force to overwrite)")
            continue
        print(write(data_dir, wines))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
